[build]
builder = "NIXPACKS"

# Tell Railway explicitly which directory to use
[project]
root = "server"

[env]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm start"
